export const ar = {
  login: 'تسجيل الدخول',
  confirm: 'تأكيد',
  mobile: 'رقم الجوال',
  password: 'كلمة المرور',
  rememberMe: 'تذكرني',
  login: 'دخول',
  forgotPassword: 'نسيت كلمة السر ؟',
  dontHaveAccount: 'لا امتلك حساب ؟ سجل الآن',
  fromCity: 'من (البلد، المدينة)',
  toCity: 'إلى (البلد، المدينة)',
  weight: 'الحمولة',
  unknown: 'غير معروف',
  category: 'الفئة',
  date: 'تاريخ الوصول',
  search: 'بحث',
  shipments: 'شحنات',
  travels: 'رحلات',
  from: 'من',
  to: 'إلى',
  dateArrived: 'تاريخ الوصول',
  show: 'عرض',
  viewProfile: 'عرض الملف الشخصي',
  main: 'الرئيسية',
  addTravelPlan: 'إضافة رحلة',
  addShipment: 'إضافة شحنة',
  orders: 'الطلبات',
  notifications: 'التنبيهات',
  travelPlans: 'الرحلات',
  shipments: 'الشحنات',
  settings: 'الإعدادات',
  paymentDetails: 'تفاصيل الدفع',
  privacyPolicy: 'شروط الاستخدام و الخصوصية',
  giveFeedback: 'أعطنا رأيك',
  shareApp: 'مشاركة التطبيق',
  logout: 'تسجيل الخروج'


}
