export const en = {
  login: 'Login',
  confirm: 'Confirm',
  mobile: 'Phone Number',
  password: 'Password',
  rememberMe: 'Remember Me',
  login: 'Login',
  forgotPassword: 'Forgot Password ?',
  dontHaveAccount: 'Don\'t Have an Account ?',
  fromCity: 'From (City, Country)',
  toCity: 'To (City, Country)',
  weight: 'Weight',
  unknown: 'Unknown',
  category: 'Category',
  date: 'Arrival Date',
  search: 'Search',
  shipments: 'Shipments',
  travels: 'Trips',
  from: 'From',
  to: 'To',
  dateArrived: 'Arrival Date',
  show: 'Show',
  viewProfile: 'View Own Profile',
  main: 'Main',
  addTravelPlan: 'Add a Trip',
  addShipment: 'Add Shipment',
  orders: 'Orders',
  notifications: 'Notifications',
  travelPlans: 'Trips',
  shipments: 'Shipments',
  settings: 'Settings',
  paymentDetails: 'Payment Details',
  privacyPolicy: 'Privacy Policy and Terms of Use',
  giveFeedback: 'Give Us Feedback',
  shareApp: 'Share App',
  logout: 'Logout'


}
